### PR TITLE
Update prerequisites for Ubuntu 20.04.

### PR DESCRIPTION
**Pull request by vkucera**
Remove `libyaml-cpp-dev`.
Add `libtbb-dev`.

### CODE REVIEW

**Comment by ktf** [comment]
please, just keep one list for ubuntu.

**Comment by vkucera** [comment]
@ktf 
> please, just keep one list for ubuntu.

The lists for 18 and 20 are different. What do you suggest?

**Comment by ktf** [comment]
set union. did they actually remove a package?

**Comment by ktf** [comment]
To clarify. `libyaml-cpp-dev` and `libtbb-dev`  are present on both. Splitting the recipe to micromanage the packages is a bad idea, IMHO.

**Comment by vkucera** [comment]
I am sorry, I still don't understand what you mean.
`libyaml-cpp-dev` is on the 18 list but must not be installed on 20.
`libtbb-dev` is not on the 18 list but must be installed on 20.
Hence the reason for making a separate list for 20.
Where do you see them present on both?

**Comment by ktf** [comment]
my point is that both should be installed everywhere and we should fix the recipes if they don't work.

**Comment by vkucera** [comment]
OK, so do you mean changing the O2 recipes so that `libyaml-cpp-dev` is always built regardless of its presence in the system and `libtbb-dev` is built if it cannot be picked up from the system?

**Comment by ktf** [comment]
Not necessarily from alibuild. My point is that there is no need to have two different system configuration for Ubuntu 18.04 or 20.04, given `libyaml-cpp-dev` and `libtbb-dev` are present in both. In particular, given we cannot ask people to uninstall packages, because they might need them for things outside our scope, the only solution is to support them being present on the system.

**Comment by vkucera** [comment]
OK. I know for sure that in order to build O2, I had to install `libtbb-dev` and uninstall `libyaml-cpp-dev`, which I had installed previously together with the rest of prerequisites from the Ubuntu 18 list.
So it is obvious that the current list does not work with the current recipes.
I don't know what is the best way to fix this, but I think this should be solved as an increasing number of people are using the latest Ubuntu LTS.

**Comment by MichaelLettrich** [comment]
Sorry, I didn't see this PR when creating mine ( #112 ). I fixed the issues for 20.04. cleaned up the prerequisites list and tested in vanilla docker containers to check if everything is fine.

**Comment by MichaelLettrich** [comment]
Resolved by #112

**Pull request closed without merging**
