### PR TITLE
Simplify build instructions

### PR DESCRIPTION
**Pull request by ktf**
* Use distribution packages for aliBuild installation where available.
* Keep `pip` as a special case.

### CODE REVIEW

**Comment by ktf** [comment]
@mpuccio who is "offline"?

**Comment by mpuccio** [comment]
Ciao @ktf, currently you and @pzhristov and @MichaelLettrich . Actually you and @pzhristov are also owner of the full thing (I think we did it in the past to make it faster in some interactions), so feel free to invite or make the changes you deem appropriate.

**Review by mpuccio — APPROVED** [review]

**Comment by ktf** [comment]
@mpuccio yes, I noticed, however apparently I am unable to merge PRs, for some reason.

**Comment by mpuccio** [comment]
@ktf merging is prevented without reviews and you cannot self review. We can remove this requirement as anyway only the usual suspects commit here.

**Pull request merged**
