### PR TITLE
Add build instructions for CentOS 7

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by rbertens** [comment]
Hi @dberzano , beginning of next week I'll likely do a clean install of CentOS7 and then also run aliBuild on it, so if you can wait a few days, I can give detailed feedback from that. 
thanks,
redmer

**Comment by dberzano** [comment]
I have already found something missing. Fixing...

**Comment by dberzano** [comment]
I can confirm that AliPhysics (using `--defaults user`) works. I am now launching the O2 build.

**Comment by dberzano** [comment]
@rbertens it would be good if you tested it using `devtoolset-7` instead of `devtoolset-6`. In principle, given the compiler's the same as on Ubuntu 18, it should work.

**Comment by dberzano** [comment]
I am proactively adding the `devtoolset-7` documentation. Will revert the last commit in case it does not work. I have started a full build of Run2 software with it.

**Comment by dberzano** [comment]
I confirm `devtoolset-7` works for AliPhysics. Trying O2 now!

**Comment by dberzano** [comment]
O2 does not compile with `devtoolset-7` due to [a bug](https://bugzilla.redhat.com/show_bug.cgi?id=1519073), I am leaving the recommendation to `devtoolset-6`.

**Comment by rbertens** [comment]
@dberzano a bit late to comment but still as confirmation: smooth build of both user and user-root6  with devtoolset-6

**Pull request merged**
