### PR TITLE
Add Docker instructions

### PR DESCRIPTION
**Pull request by dberzano**
- [x] Add instructions on increasing Docker VM memory on macOS
- [x] Use same directory path inside/outside Docker VM to avoid broken `MIRROR` links

### CODE REVIEW

**Comment by dberzano** [comment]
I'd like @dstocco to have a look before merging :-)

**Comment by dberzano** [comment]
(This means: @rbertens do not merge yet.)

**Comment by dstocco** [comment]
Ciao @dberzano ,
the instructions are clear indeed. I followed them and I'm now in the process of compiling the code with centos:7!
Just one point (which I'm not sure if it is related to my install or a general one). When creating the container, you map ~/alice to /alice. However, let's suppose that we have sources in ~/alice. They will point to MIRROR in ~/alice/sw. If you map to /alice, the link between the sources and MIRROR will be broken. Wouldn't it be better to map keeping exactly the same path, i.e.
`-v ~/alice:$HOME/alice`
?
Otherwise, it's fine with me.
Thanks a lot!!!
Ciao,
Diego

**Comment by dstocco** [comment]
Hi @dberzano ,
actually I've tried the run alibuild as well, but got one issue when compiling root (see relevant part of log below). 
Looking in the web, it turn out that it might be related to a memory issue. 

I was compiling with `aliBuild -z -w $ALIBUILD_WORK_DIR -j6 --defaults alo build`
Probably it does not like the -j6 (?)
Will try tomorrow with -j1 and let you know. If it works, maybe it can be added to the instructions...

Cheers,
Diego

`/clangParse.dir/ParseExpr.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/PPExpressions.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
interpreter/llvm/src/tools/clang/lib/AST/CMakeFiles/clangAST.dir/build.make:110: recipe for target 'interpreter/llvm/src/tools/clang/lib/AST/CMakeFiles/clangAST.dir/ASTContext.cpp.o' failed
make[2]: *** [interpreter/llvm/src/tools/clang/lib/AST/CMakeFiles/clangAST.dir/ASTContext.cpp.o] Error 4
make[2]: *** Deleting file 'interpreter/llvm/src/tools/clang/lib/AST/CMakeFiles/clangAST.dir/ASTContext.cpp.o'
CMakeFiles/Makefile2:7458: recipe for target 'interpreter/llvm/src/tools/clang/lib/AST/CMakeFiles/clangAST.dir/all' failed
make[1]: *** [interpreter/llvm/src/tools/clang/lib/AST/CMakeFiles/clangAST.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/TokenKinds.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/CodeCompleteConsumer.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/DeclSpec.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/PPLexerChange.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/Version.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGAtomic.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/VersionTuple.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/VirtualFileSystem.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/PPMacroExpansion.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Parse/CMakeFiles/clangParse.dir/ParseExprCXX.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/Warnings.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/DelayedDiagnostic.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/XRayLists.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/IdentifierResolver.cpp.o
[ 54%] Linking CXX static library ../../../../lib/libclangBasic.a
[ 54%] Built target clangBasic
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGBlocks.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/PTHLexer.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/JumpDiagnostics.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/Pragma.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGBuiltin.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Parse/CMakeFiles/clangParse.dir/ParseInit.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/PreprocessingRecord.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Parse/CMakeFiles/clangParse.dir/ParseObjc.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/Preprocessor.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/build.make:134: recipe for target 'interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGBuiltin.cpp.o' failed
make[2]: *** [interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGBuiltin.cpp.o] Error 4
make[2]: *** Deleting file 'interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGBuiltin.cpp.o'
make[2]: *** Waiting for unfinished jobs....
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/MultiplexExternalSemaSource.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/PreprocessorLexer.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Parse/CMakeFiles/clangParse.dir/ParseOpenMP.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/Scope.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/ScratchBuffer.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/ScopeInfo.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/TokenConcatenation.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/Sema.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Parse/CMakeFiles/clangParse.dir/ParsePragma.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Lex/CMakeFiles/clangLex.dir/TokenLexer.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/SemaAccess.cpp.o
[ 54%] Linking CXX static library ../../../../lib/libclangLex.a
[ 54%] Built target clangLex
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/SemaAttr.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/build.make:86: recipe for target 'interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGAtomic.cpp.o' failed
make[2]: *** [interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGAtomic.cpp.o] Error 4
make[2]: *** Deleting file 'interpreter/llvm/src/tools/clang/lib/CodeGen/CMakeFiles/clangCodeGen.dir/CGAtomic.cpp.o'
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Parse/CMakeFiles/clangParse.dir/ParseStmt.cpp.o
[ 54%] Building CXX object interpreter/llvm/src/tools/clang/lib/Sema/CMakeFiles/clangSema.dir/SemaCXXScopeSpec.cpp.o
`

**Comment by aphecetche** [comment]
@dstocco Did you increased, in the Docker app, the memory you're allowing for the Docker Virtual Machine on your Mac or are you using the default value ? (was 2 GB if I remember correctly on my machine)   

capture d ecran 2018-04-10 a 08 25 09

**Comment by dstocco** [comment]
Hi @aphecetche ,
I use the default: 4 CPUs, 2 GB RAM, 1 GB swap...
Cheers,
Diego

**Comment by dberzano** [comment]
Concerning the build issue, it's likely an OOM as @aphecetche pointed out; indeed building some software requires loads of memory, but also running it as well. By default, this limitation does not exist on Linux, but Docker for macOS silently runs your containers inside a Linux VM, with memory limitations. I think we need to explain how to increase this memory.

As for the `MIRROR` problem, @dstocco, you are absolutely right - of course the problem shows up in case you use aliBuild both on your host and in your container.

I have added a TODO at the top and will update the doc accordingly. Thanks for your useful feedback!

**Comment by dberzano** [comment]
@dstocco @aphecetche out of curiosity:

* how much RAM + CPU did you allot for your Docker VM?
* what `-j` option do you use?

I am thinking of adding suggested values to the doc.

**Comment by dberzano** [comment]
@dstocco @aphecetche your comments have been addressed, thanks!

@rbertens any comment? If not, it's ready to be merged.

**Pull request merged**
