### PR TITLE
Fix problem in using ROOT5/6 at the same time

### PR DESCRIPTION
**Pull request by dberzano**
Add the use of `-z <blah>` to aliBuild

### CODE REVIEW

**Comment by dberzano** [comment]
@amohanty these are the updated instructions, fixing (hopefully!) your problem!

**Comment by dberzano** [comment]
@mpuccio so the problem is that aliBuild _should_ use different build directories for different defaults, but it doesn't. Given that the problem should be, admittedly, fixed upstream (and probably there will be long discussions on how to do it properly), in the meanwhile the updated doc provides users with a working solution.

I myself had the problem following my own instructions, and so did @amohanty 😄 

Thanks for approving!

**Comment by MycrofD** [comment]
@dberzano you may delete this comment later, but @amohanty is not me!

**Comment by dberzano** [comment]
Woops! Apologies! :smile:

**Pull request merged**
