### PR TITLE
prereq-ubuntu.md - python3 prerequisite update ?

### PR DESCRIPTION
**Pull request by maireiphc**
To me, this has been needed under 18.04 LTS.

### CODE REVIEW

**Review by MichaelLettrich — COMMENTED** [review]
I cannot reproduce. Is this for run 2 or for O2 ?

**Comment by maireiphc** [comment]
Hello Michael,

It has been needed for Run-2 build (AliRoot, AliPhysics). The modification that I introduced here in the documentation is a suggestion coming from the log directly, upon compilation failure.

**Comment by MichaelLettrich** [comment]
Thanks, so far I've only been working with O2. I'll try to reproduce.

**Comment by MichaelLettrich** [comment]
I've built with the `next-root6` preset and the latest alidist, AliROOT and AliPhysiscs version according to my updated instructions without issues on 18.04 starting from a vanilla docker image. What did you use?

**Comment by mpuccio** [comment]
Ciao @maireiphc, I have just reinstalled everything from scratch on Ubuntu 20.04 and I did not need this. Since we do not have other reports requiring this I would close here (I hope we will not regret this :) )

**Pull request closed without merging**
