### PR TITLE
Improve macOS documentation

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@mconcas @mpuccio any objections? I think the less blah blah we have, the better.

**Comment by mconcas** [comment]
> @mconcas @mpuccio any objections? I think the less blah blah we have, the better.

I'd also go for being focused on useful information.

**Review by mpuccio — APPROVED** [review]
Fine with me!

**Comment by ktf** [comment]
Thanks!

**Pull request merged**
