### PR TITLE
Use meta RPM package to install dependencies

### PR DESCRIPTION
**Pull request by ktf**
Advantages of this approach:

* Allows unification different build instructions / recipes and use .
* We can update the installation of new tools and simply ask people to yum update.
* Shorter instructions.

### CODE REVIEW

**Comment by ktf** [comment]
@mconcas you might want to do this also for the alidock provisioning.

**Comment by mconcas** [comment]
> @mconcas you might want to do this also for the alidock provisioning.
Are you planning to update the `provision.sh` script in thez slc7-builder container recipe as well?
The alidock container is derived from that one, so it would just require a container rebuild.

**Comment by ktf** [comment]
Yes, that's the plan. Ok, nothing to do on your side, then. I will notify you when we update slc7- builder.

**Comment by mpuccio** [comment]
Ciao @ktf , is this ready to be merged?

**Review by mpuccio — APPROVED** [review]

**Comment by ktf** [comment]
Yes, sorry. I finally gave a last check with O2 and it installs everything, downloading the prebuilt tarballs, just fine.

**Pull request merged**
