### PR TITLE
Add Fedora 27 documentation

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
Currently testing, do not merge. AliRoot/AliPhysics passed (with a trick involving downgrading OpenSSL...), O2's in progress. GCC is v7.2.1.

**Comment by dberzano** [comment]
22 days later, here's the update. Vc caused a problem in building O2. Current version of alidist has an updated Vc that does not have the problem any longer. So, the instructions here work. @rbertens if you have no objections, could you please add your review? Thanks!

**Comment by rbertens** [comment]
Hi Dario, 
Is the instruction

docker run fedora:27 bash

correct? 
I'm running on Cenos7, and the command immediately terminates (but I have limited experience here)

**Comment by dberzano** [comment]
OK, so this is rather a way to give a hint on what's the name of the Docker Hub image to use, but the command does not provide with any instant gratification.

One possible working command line is:

```bash
docker -it --rm fedora:27 bash
```

Now the problem with containers is that they are disposable, but you'll probably want to keep your customization here. We have different options.

1. We provide ALICE containers with all the prerequisites already satisfied.
2. We explain how to permanently save a container after customizing it.
3. We explain the correct way to customize a container (I am referring to Dockerfiles)
4. We explain how to mount external volumes visible both in the container and outside (the `-v` option)

We would actually need a different documentation page on Docker only. I suggest, if you agree, that I amend the current Docker section by simply specifying _this is the Docker image we use_ without any suggested command line, and leave a more thorough Docker doc for later.

Note that all the other prerequisites pages (macOS excepted) need to be amended.

**Comment by rbertens** [comment]
That clarifies. Indeed I would phrase it then saying this is just the docker image, to avoid that someone blindly copy-pastes the line and gets stuck. 

The instructions are good btw - prerequisites are met and the build goes through fine (well, it's nearly completed on my machine)

**Comment by dberzano** [comment]
I have rephrased the Docker paragraph.

**Comment by dberzano** [comment]
#16 clarifies the use of Docker images for CentOS 7 and Ubuntu.

**Pull request merged**
